#pragma once

#include <string>
#include <unordered_map>

enum Element : int {
    H = 1,
    He,
    Li,
    Be,
    B,
    C,
    N,
    O,
    F,
    Ne,
    Na,
    Mg,
    Al,
    Si,
    P,
    S,
    Cl,
    Ar,
    K,
    Ca,
    Sc,
    Ti,
    V,
    Cr,
    Mn,
    Fe,
    Co,
    Ni,
    Cu,
    Zn,
    Ga,
    Ge,
    As,
    Se,
    Br,
    Kr,
    Rb,
    Sr,
    Y,
    Zr,
    Nb,
    Mo,
    Tc,
    Ru,
    Rh,
    Pd,
    Ag,
    Cd,
    In,
    Sn,
    Sb,
    Te,
    I,
    Xe,
    Cs,
    Ba,
    La,
    Ce,
    Pr,
    Nd,
    Pm,
    Sm,
    Eu,
    Gd,
    Tb,
    Dy,
    Ho,
    Er,
    Tm,
    Yb,
    Lu,
    Hf,
    Ta,
    W,
    Re,
    Os,
    Ir,
    Pt,
    Au,
    Hg,
    Tl,
    Pb,
    Bi,
    Po,
    At,
    Rn,
    Fr,
    Ra,
    Ac,
    Th,
    Pa,
    U,
    Np,
    Pu,
    Am,
    Cm,
    Bk,
    Cf,
    Es,
    Fm,
    Md,
    No,
    Lr,
    Rf,
    Db,
    Sg,
    Bh,
    Hs,
    Mt,
    Ds,
    Rg,
    Cn,
    Nh,
    Fl,
    Mc,
    Lv,
    Ts,
    Og
};

/**
 * @brief Get the element name object
 *
 * @param element
 * @return std::string Full name of the element
 */
inline std::string get_element_name(Element element) {
    static const std::unordered_map<Element, std::string> element_names = {
        {Element::H, "Hydrogen"},      {Element::He, "Helium"},
        {Element::Li, "Lithium"},      {Element::Be, "Beryllium"},
        {Element::B, "Boron"},         {Element::C, "Carbon"},
        {Element::N, "Nitrogen"},      {Element::O, "Oxygen"},
        {Element::F, "Fluorine"},      {Element::Ne, "Neon"},
        {Element::Na, "Sodium"},       {Element::Mg, "Magnesium"},
        {Element::Al, "Aluminum"},     {Element::Si, "Silicon"},
        {Element::P, "Phosphorus"},    {Element::S, "Sulfur"},
        {Element::Cl, "Chlorine"},     {Element::Ar, "Argon"},
        {Element::K, "Potassium"},     {Element::Ca, "Calcium"},
        {Element::Sc, "Scandium"},     {Element::Ti, "Titanium"},
        {Element::V, "Vanadium"},      {Element::Cr, "Chromium"},
        {Element::Mn, "Manganese"},    {Element::Fe, "Iron"},
        {Element::Co, "Cobalt"},       {Element::Ni, "Nickel"},
        {Element::Cu, "Copper"},       {Element::Zn, "Zinc"},
        {Element::Ga, "Gallium"},      {Element::Ge, "Germanium"},
        {Element::As, "Arsenic"},      {Element::Se, "Selenium"},
        {Element::Br, "Bromine"},      {Element::Kr, "Krypton"},
        {Element::Rb, "Rubidium"},     {Element::Sr, "Strontium"},
        {Element::Y, "Yttrium"},       {Element::Zr, "Zirconium"},
        {Element::Nb, "Niobium"},      {Element::Mo, "Molybdenum"},
        {Element::Tc, "Technetium"},   {Element::Ru, "Ruthenium"},
        {Element::Rh, "Rhodium"},      {Element::Pd, "Palladium"},
        {Element::Ag, "Silver"},       {Element::Cd, "Cadmium"},
        {Element::In, "Indium"},       {Element::Sn, "Tin"},
        {Element::Sb, "Antimony"},     {Element::Te, "Tellurium"},
        {Element::I, "Iodine"},        {Element::Xe, "Xenon"},
        {Element::Cs, "Cesium"},       {Element::Ba, "Barium"},
        {Element::La, "Lanthanum"},    {Element::Ce, "Cerium"},
        {Element::Pr, "Praseodymium"}, {Element::Nd, "Neodymium"},
        {Element::Pm, "Promethium"},   {Element::Sm, "Samarium"},
        {Element::Eu, "Europium"},     {Element::Gd, "Gadolinium"},
        {Element::Tb, "Terbium"},      {Element::Dy, "Dysprosium"},
        {Element::Ho, "Holmium"},      {Element::Er, "Erbium"},
        {Element::Tm, "Thulium"},      {Element::Yb, "Ytterbium"},
        {Element::Lu, "Lutetium"},     {Element::Hf, "Hafnium"},
        {Element::Ta, "Tantalum"},     {Element::W, "Tungsten"},
        {Element::Re, "Rhenium"},      {Element::Os, "Osmium"},
        {Element::Ir, "Iridium"},      {Element::Pt, "Platinum"},
        {Element::Au, "Gold"},         {Element::Hg, "Mercury"},
        {Element::Tl, "Thallium"},     {Element::Pb, "Lead"},
        {Element::Bi, "Bismuth"},      {Element::Po, "Polonium"},
        {Element::At, "Astatine"},     {Element::Rn, "Radon"},
        {Element::Fr, "Francium"},     {Element::Ra, "Radium"},
        {Element::Ac, "Actinium"},     {Element::Th, "Thorium"},
        {Element::Pa, "Protactinium"}, {Element::U, "Uranium"},
        {Element::Np, "Neptunium"},    {Element::Pu, "Plutonium"},
        {Element::Am, "Americium"},    {Element::Cm, "Curium"},
        {Element::Bk, "Berkelium"},    {Element::Cf, "Californium"},
        {Element::Es, "Einsteinium"},  {Element::Fm, "Fermium"},
        {Element::Md, "Mendelevium"},  {Element::No, "Nobelium"},
        {Element::Lr, "Lawrencium"},   {Element::Rf, "Rutherfordium"},
        {Element::Db, "Dubnium"},      {Element::Sg, "Seaborgium"},
        {Element::Bh, "Bohrium"},      {Element::Hs, "Hassium"},
        {Element::Mt, "Meitnerium"},   {Element::Ds, "Darmstadtium"},
        {Element::Rg, "Roentgenium"},  {Element::Cn, "Copernicium"},
        {Element::Nh, "Nihonium"},     {Element::Fl, "Flerovium"},
        {Element::Mc, "Moscovium"},    {Element::Lv, "Livermorium"},
        {Element::Ts, "Tennessine"},   {Element::Og, "Oganesson"}};

    auto it = element_names.find(element);
    return it != element_names.end() ? it->second : "Unknown";
}
