#pragma once

#include <string>
#include <unordered_map>

enum class Element {
    H,
    He,
    Li,
    Be,
    B,
    C,
    N,
    O,
    F,
    Ne,
    Na,
    Mg,
    Al,
    Si,
    P,
    S,
    Cl,
    Ar,
    K,
    Ca,
    Sc,
    Ti,
    V,
    Cr,
    Mn,
    Fe,
    Co,
    Ni,
    Cu,
    Zn,
    Ga,
    Ge,
    As,
    Se,
    Br,
    Kr,
    Rb,
    Sr,
    Y,
    Zr,
    Nb,
    Mo,
    Tc,
    Ru,
    Rh,
    Pd,
    Ag,
    Cd,
    In,
    Sn,
    Sb,
    Te,
    I,
    Xe,
    Cs,
    Ba,
    La,
    Ce,
    Pr,
    Nd,
    Pm,
    Sm,
    Eu,
    Gd,
    Tb,
    Dy,
    Ho,
    Er,
    Tm,
    Yb,
    Lu,
    Hf,
    Ta,
    W,
    Re,
    Os,
    Ir,
    Pt,
    Au,
    Hg,
    Tl,
    Pb,
    Bi,
    Po,
    At,
    Rn,
    Fr,
    Ra,
    Ac,
    Th,
    Pa,
    U,
    Np,
    Pu,
    Am,
    Cm,
    Bk,
    Cf,
    Es,
    Fm,
    Md,
    No,
    Lr,
    Rf,
    Db,
    Sg,
    Bh,
    Hs,
    Mt,
    Ds,
    Rg,
    Cn,
    Nh,
    Fl,
    Mc,
    Lv,
    Ts,
    Og
};

inline int get_element_charge(Element element) {
    static const std::unordered_map<Element, int> element_charges = {
        {Element::H, 1},    {Element::He, 2},   {Element::Li, 3},
        {Element::Be, 4},   {Element::B, 5},    {Element::C, 6},
        {Element::N, 7},    {Element::O, 8},    {Element::F, 9},
        {Element::Ne, 10},  {Element::Na, 11},  {Element::Mg, 12},
        {Element::Al, 13},  {Element::Si, 14},  {Element::P, 15},
        {Element::S, 16},   {Element::Cl, 17},  {Element::Ar, 18},
        {Element::K, 19},   {Element::Ca, 20},  {Element::Sc, 21},
        {Element::Ti, 22},  {Element::V, 23},   {Element::Cr, 24},
        {Element::Mn, 25},  {Element::Fe, 26},  {Element::Co, 27},
        {Element::Ni, 28},  {Element::Cu, 29},  {Element::Zn, 30},
        {Element::Ga, 31},  {Element::Ge, 32},  {Element::As, 33},
        {Element::Se, 34},  {Element::Br, 35},  {Element::Kr, 36},
        {Element::Rb, 37},  {Element::Sr, 38},  {Element::Y, 39},
        {Element::Zr, 40},  {Element::Nb, 41},  {Element::Mo, 42},
        {Element::Tc, 43},  {Element::Ru, 44},  {Element::Rh, 45},
        {Element::Pd, 46},  {Element::Ag, 47},  {Element::Cd, 48},
        {Element::In, 49},  {Element::Sn, 50},  {Element::Sb, 51},
        {Element::Te, 52},  {Element::I, 53},   {Element::Xe, 54},
        {Element::Cs, 55},  {Element::Ba, 56},  {Element::La, 57},
        {Element::Ce, 58},  {Element::Pr, 59},  {Element::Nd, 60},
        {Element::Pm, 61},  {Element::Sm, 62},  {Element::Eu, 63},
        {Element::Gd, 64},  {Element::Tb, 65},  {Element::Dy, 66},
        {Element::Ho, 67},  {Element::Er, 68},  {Element::Tm, 69},
        {Element::Yb, 70},  {Element::Lu, 71},  {Element::Hf, 72},
        {Element::Ta, 73},  {Element::W, 74},   {Element::Re, 75},
        {Element::Os, 76},  {Element::Ir, 77},  {Element::Pt, 78},
        {Element::Au, 79},  {Element::Hg, 80},  {Element::Tl, 81},
        {Element::Pb, 82},  {Element::Bi, 83},  {Element::Po, 84},
        {Element::At, 85},  {Element::Rn, 86},  {Element::Fr, 87},
        {Element::Ra, 88},  {Element::Ac, 89},  {Element::Th, 90},
        {Element::Pa, 91},  {Element::U, 92},   {Element::Np, 93},
        {Element::Pu, 94},  {Element::Am, 95},  {Element::Cm, 96},
        {Element::Bk, 97},  {Element::Cf, 98},  {Element::Es, 99},
        {Element::Fm, 100}, {Element::Md, 101}, {Element::No, 102},
        {Element::Lr, 103}, {Element::Rf, 104}, {Element::Db, 105},
        {Element::Sg, 106}, {Element::Bh, 107}, {Element::Hs, 108},
        {Element::Mt, 109}, {Element::Ds, 110}, {Element::Rg, 111},
        {Element::Cn, 112}, {Element::Nh, 113}, {Element::Fl, 114},
        {Element::Mc, 115}, {Element::Lv, 116}, {Element::Ts, 117},
        {Element::Og, 118}};

    auto it = element_charges.find(element);
    return it != element_charges.end() ? it->second : -1;
}

inline std::string get_element_name(Element element) {
    static const std::unordered_map<Element, std::string> element_names = {
        {Element::H, "Hydrogen"},      {Element::He, "Helium"},
        {Element::Li, "Lithium"},      {Element::Be, "Beryllium"},
        {Element::B, "Boron"},         {Element::C, "Carbon"},
        {Element::N, "Nitrogen"},      {Element::O, "Oxygen"},
        {Element::F, "Fluorine"},      {Element::Ne, "Neon"},
        {Element::Na, "Sodium"},       {Element::Mg, "Magnesium"},
        {Element::Al, "Aluminum"},     {Element::Si, "Silicon"},
        {Element::P, "Phosphorus"},    {Element::S, "Sulfur"},
        {Element::Cl, "Chlorine"},     {Element::Ar, "Argon"},
        {Element::K, "Potassium"},     {Element::Ca, "Calcium"},
        {Element::Sc, "Scandium"},     {Element::Ti, "Titanium"},
        {Element::V, "Vanadium"},      {Element::Cr, "Chromium"},
        {Element::Mn, "Manganese"},    {Element::Fe, "Iron"},
        {Element::Co, "Cobalt"},       {Element::Ni, "Nickel"},
        {Element::Cu, "Copper"},       {Element::Zn, "Zinc"},
        {Element::Ga, "Gallium"},      {Element::Ge, "Germanium"},
        {Element::As, "Arsenic"},      {Element::Se, "Selenium"},
        {Element::Br, "Bromine"},      {Element::Kr, "Krypton"},
        {Element::Rb, "Rubidium"},     {Element::Sr, "Strontium"},
        {Element::Y, "Yttrium"},       {Element::Zr, "Zirconium"},
        {Element::Nb, "Niobium"},      {Element::Mo, "Molybdenum"},
        {Element::Tc, "Technetium"},   {Element::Ru, "Ruthenium"},
        {Element::Rh, "Rhodium"},      {Element::Pd, "Palladium"},
        {Element::Ag, "Silver"},       {Element::Cd, "Cadmium"},
        {Element::In, "Indium"},       {Element::Sn, "Tin"},
        {Element::Sb, "Antimony"},     {Element::Te, "Tellurium"},
        {Element::I, "Iodine"},        {Element::Xe, "Xenon"},
        {Element::Cs, "Cesium"},       {Element::Ba, "Barium"},
        {Element::La, "Lanthanum"},    {Element::Ce, "Cerium"},
        {Element::Pr, "Praseodymium"}, {Element::Nd, "Neodymium"},
        {Element::Pm, "Promethium"},   {Element::Sm, "Samarium"},
        {Element::Eu, "Europium"},     {Element::Gd, "Gadolinium"},
        {Element::Tb, "Terbium"},      {Element::Dy, "Dysprosium"},
        {Element::Ho, "Holmium"},      {Element::Er, "Erbium"},
        {Element::Tm, "Thulium"},      {Element::Yb, "Ytterbium"},
        {Element::Lu, "Lutetium"},     {Element::Hf, "Hafnium"},
        {Element::Ta, "Tantalum"},     {Element::W, "Tungsten"},
        {Element::Re, "Rhenium"},      {Element::Os, "Osmium"},
        {Element::Ir, "Iridium"},      {Element::Pt, "Platinum"},
        {Element::Au, "Gold"},         {Element::Hg, "Mercury"},
        {Element::Tl, "Thallium"},     {Element::Pb, "Lead"},
        {Element::Bi, "Bismuth"},      {Element::Po, "Polonium"},
        {Element::At, "Astatine"},     {Element::Rn, "Radon"},
        {Element::Fr, "Francium"},     {Element::Ra, "Radium"},
        {Element::Ac, "Actinium"},     {Element::Th, "Thorium"},
        {Element::Pa, "Protactinium"}, {Element::U, "Uranium"},
        {Element::Np, "Neptunium"},    {Element::Pu, "Plutonium"},
        {Element::Am, "Americium"},    {Element::Cm, "Curium"},
        {Element::Bk, "Berkelium"},    {Element::Cf, "Californium"},
        {Element::Es, "Einsteinium"},  {Element::Fm, "Fermium"},
        {Element::Md, "Mendelevium"},  {Element::No, "Nobelium"},
        {Element::Lr, "Lawrencium"},   {Element::Rf, "Rutherfordium"},
        {Element::Db, "Dubnium"},      {Element::Sg, "Seaborgium"},
        {Element::Bh, "Bohrium"},      {Element::Hs, "Hassium"},
        {Element::Mt, "Meitnerium"},   {Element::Ds, "Darmstadtium"},
        {Element::Rg, "Roentgenium"},  {Element::Cn, "Copernicium"},
        {Element::Nh, "Nihonium"},     {Element::Fl, "Flerovium"},
        {Element::Mc, "Moscovium"},    {Element::Lv, "Livermorium"},
        {Element::Ts, "Tennessine"},   {Element::Og, "Oganesson"}};

    auto it = element_names.find(element);
    return it != element_names.end() ? it->second : "Unknown";
}
